"""Modify SalaryDetails table

Revision ID: a850733fb557
Revises: 
Create Date: 2024-01-02 03:33:56.419769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a850733fb557'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_details',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Integer(), nullable=False),
    sa.Column('taxes', sa.Integer(), nullable=False),
    sa.Column('bonuses', sa.Integer(), nullable=False),
    sa.Column('allowances', sa.Integer(), nullable=False),
    sa.Column('total_salary', sa.Integer(), nullable=False),
    sa.Column('working_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['user_registration.Email'], ),
    sa.PrimaryKeyConstraint('email', 'month', 'year'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salary_details')
    # ### end Alembic commands ###
